theme = "awesome-identity"
baseURL = "https://bpaz.dev"
title = "Borja Paz Rodríguez | Software Engineer"
languageCode = "en-US"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

# Google Analytics tracking ID
googleAnalytics = "UA-187507362-1"

## Crisp Configurations
[params.crisp]
websiteId = "ef5eb84e-8670-4770-9783-2e04afcd55dc"
# Change the chatbox color theme
color = "red"
# Reverse the chatbox position
reversePosition = false
# Hide chatbox on mobile devices
hideOnMobile = false
# Hide chatbox on support away
hideOnAway = false
# Hide chatbox on vacation
hideVacation = false


## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
description = "Software Engineer at Plexus Tech"
keywords = "borjapazr, borja, borja.pazrodriguez, borja, paz, rodriguez, devops, backend, infrastructure, frontend, engineer, developer, architect"
images = ["/images/profile.png"]


## Profile Configurations
[params.profile]
bio = """
  👨‍👩‍👦‍👦 Son of a hairdresser and a farmer
  🔐 Escape room enthusiast and part of [Skape Squad](https://skapesquad.com)
  ❤️ Love programming and cinema
  """
portrait = "/images/profile.png"
firstname = "Borja"
lastname = "Paz Rodríguez"
title = "Software Engineer at Plexus Tech"


## Contacts Configurations
[params.contacts]
email = "hello@marsmachine.space"
github = "borjapazr"
twitter = "borjapazr"
linkedin = "borjapazr"
# keybase = "borjapazr"
# facebook = "borjapazr"
stackoverflow = "6112286"
instagram = "borjapazr"
# medium = "borjapazr"
# quora = "borjapazr"
# dribbble = "borjapazr"
# behance = "borjapazr"


## Actions Configurations
[[params.actions]]
name = "Review My CV"
url = "https://mnf.red/borjapazr"
[[params.actions]]
name = "Ask Me Anything"
url = "https://github.com/borjapazr/borjapazr/issues"


## Footer Configurations
[params.footer]
copyright = "© 2023 Borja Paz Rodríguez. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
poweredBy = true


## Privacy Configurations (GDPR)
[privacy]
[privacy.googleAnalytics]
disable = false
# Make the users’ IP addresses are anonymized within Google Analytics
anonymizeIP = false
# Make the GA templates respect the “Do Not Track” HTTP header
respectDoNotTrack = false
# Disable the use of Cookies and use Session Storage to Store the GA Client ID
useSessionStorage = false
